### ISSUE TITLE
Hard-coded IP addresses are returning server errors

### ISSUE THREAD

**Issue by socratesone** [prusnak/gimp-plugin-gaugan#1]
In your file, it looks like you've hard-coded the IP address of the API, but I'm not able to access it.
`
Traceback (most recent call last):
  File "C:\Program Files\GIMP 2\32\lib\gimp\2.0\python/gimpfu.py", line 740, in response
    dialog.res = run_script(params)
  File "C:\Program Files\GIMP 2\32\lib\gimp\2.0\python/gimpfu.py", line 361, in run_script
    return apply(function, params)
  File "C:\Users\josha\AppData\Roaming\GIMP\2.10\plug-ins\gaugan.py", line 120, in python_gaugan
    jpg = gaugan.convert(data, style)
  File "C:\Users\josha\AppData\Roaming\GIMP\2.10\plug-ins\gaugan.py", line 105, in convert
    multipart=True,
  File "C:\Users\josha\AppData\Roaming\GIMP\2.10\plug-ins\gaugan.py", line 92, in __request
    response = urllib2.urlopen(request)
  File "C:\Program Files\GIMP 2\32\lib\python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\GIMP 2\32\lib\python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "C:\Program Files\GIMP 2\32\lib\python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Program Files\GIMP 2\32\lib\python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "C:\Program Files\GIMP 2\32\lib\python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Program Files\GIMP 2\32\lib\python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 500: INTERNAL SERVER ERROR
`

**Comment by prusnak** [comment]
There was a glitch on the Nvidia servers. Please reopen if you still see the issue.
