### ISSUE TITLE
An error occurred running python_fu_gaugan

### ISSUE THREAD

**Issue by mrtkp9993** [prusnak/gimp-plugin-gaugan#3]
I am getting an error while running the plugin. I am using Mac OS X 10.15 and GIMP 2.10.

```
Traceback (most recent call last):
  File "/Applications/GIMP-2.10.app/Contents/Resources/lib/gimp/2.0/python/gimpfu.py", line 740, in response
    dialog.res = run_script(params)
  File "/Applications/GIMP-2.10.app/Contents/Resources/lib/gimp/2.0/python/gimpfu.py", line 361, in run_script
    return apply(function, params)
  File "/Users/muratkoptur/Library/Application Support/GIMP/2.10/plug-ins/gaugan.py", line 122, in python_gaugan
    jpg = gaugan.convert(data, style)
  File "/Users/muratkoptur/Library/Application Support/GIMP/2.10/plug-ins/gaugan.py", line 101, in convert
    "imageBase64": "data:image/png;base64," + base64.b64encode(image).decode()
  File "/Users/muratkoptur/Library/Application Support/GIMP/2.10/plug-ins/gaugan.py", line 94, in __request
    response = urllib2.urlopen(request)
  File "/Applications/GIMP-2.10.app/Contents/Resources/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/Applications/GIMP-2.10.app/Contents/Resources/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/Applications/GIMP-2.10.app/Contents/Resources/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/Applications/GIMP-2.10.app/Contents/Resources/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/Applications/GIMP-2.10.app/Contents/Resources/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/Applications/GIMP-2.10.app/Contents/Resources/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 60] Operation timed out>
```

**Comment by prusnak** [comment]
Try again, sometimes the nVidia servers are not running

**Comment by mrtkp9993** [comment]
Still getting the same error, I tried many times today.

**Comment by prusnak** [comment]
The backend servers have changed - fixed in https://github.com/prusnak/gimp-plugin-gaugan/commit/e65e0cadaef6a45cdfce98ddd01abeaef71b8644

Please download the updated version of gaugan.py - it should work now.

Thank you for the report!
