### ISSUE TITLE
An error occurred in python_fu_gaugan while applying GauGAN

### ISSUE THREAD

**Issue by PsychicA** [prusnak/gimp-plugin-gaugan#4]
I am getting an error while running the plugin. I am using Windows 10 and GIMP 2.10.30

```
Traceback (most recent call last):
  File "C:\Program Files\GIMP 2\lib\gimp\2.0\python/gimpfu.py", line 740, in response
    dialog.res = run_script(params)
  File "C:\Program Files\GIMP 2\lib\gimp\2.0\python/gimpfu.py", line 361, in run_script
    return apply(function, params)
  File "C:\Program Files\GIMP 2\lib\gimp\2.0\plug-ins\gaugan.py", line 120, in python_gaugan
    jpg = gaugan.convert(data, style)
  File "C:\Program Files\GIMP 2\lib\gimp\2.0\plug-ins\gaugan.py", line 99, in convert
    "imageBase64": "data:image/png;base64," + base64.b64encode(image).decode()
  File "C:\Program Files\GIMP 2\lib\gimp\2.0\plug-ins\gaugan.py", line 92, in __request
    response = urllib2.urlopen(request)
  File "C:\Program Files\GIMP 2\lib\python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\GIMP 2\lib\python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "C:\Program Files\GIMP 2\lib\python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "C:\Program Files\GIMP 2\lib\python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Program Files\GIMP 2\lib\python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "C:\Program Files\GIMP 2\lib\python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
```

**Comment by prusnak** [comment]
GauGAN has been obsoleted by GauGAN2 so I suppose that nVidia turned off their GauGAN1 servers.

It will take some time until this tool is compatible with GauGAN2 ...
